
---
version: '3.7'
services:
  maven:
    build:
      context: .
      dockerfile: DockerfileAlpine
    volumes:
      - type: volume
        source: webapps
        target: /usr/local/tomcat/webapps

  web:
    image: tomcat:9
    volumes:
      - type: volume
        source: webapps
        target: /usr/local/tomcat/webapps/
    ports:
      - "8082:8080"
volumes:
  webapps:

---
